### ISSUE TITLE
Minimum PHP version error

### ISSUE THREAD

**Issue by letasync** [carolinan/fullsiteediting#13]
Hi,
What is the minimum PHP version required for the advance theme generated using theme generator. 
I got error with PHP 7.3.5
**My Test Env
Local Flywheel
Wordpress 5.9-RC3-52619**
![minimum php version](https://user-images.githubusercontent.com/3252351/151010055-20b1aff7-f3b5-419b-8dee-fc55a0685201.png)

**Comment by hchouhan** [comment]
My guess is PHP 7.4.

**Comment by letasync** [comment]
Thanks 
Working with PHP 7.4.1 upto 8.0.0
