### ISSUE TITLE
Wrong code for disabling gradients in single block

### ISSUE THREAD

**Issue by hchouhan** [carolinan/fullsiteediting#14]
On https://fullsiteediting.com/lessons/theme-json-color-options/,

The code of how to disable gradients in a single block is incorrect. 

<img width="961" alt="Screen Shot 2022-01-26 at 10 56 28 AM" src="https://user-images.githubusercontent.com/1587151/151108628-a5972ea0-6398-4610-9bc6-958022310327.png">

**Comment by carolinan** [comment]
Thank you! ❤️ 
I have updated it to correctly use gradients instead of duotone.

(It also does not seem to disable it for the cover block overlay, 🤔 so I changed the example to group)
