### ISSUE TITLE
Problem with tooling

### ISSUE THREAD

**Issue by KristofferBroberg** [carolinan/fullsiteediting#18]
Hi!

What version of Node should I run in order get the tooling to work? Tried `npm install` and `npm update` but I can't get it to work. Seems to a dependency problem with eslint and stylelint. Tried different version of Node as well. Any ideas?

**Comment by carolinan** [comment]
Hi,
are you able to share the errors?

**Comment by carolinan** [comment]
Because I work with Gutenberg, I use the highest version that Gutenberg supports which is npm 6.14.16. With this, I am using
Node.js v14.17.3. 
I do not see any conflicts on Windows, I'll try again on mac to see if I get a different result.

**Comment by KristofferBroberg** [comment]
I reverted back to the versions you mention above, and then ran npm install. Less errors this time around but still:

`npm WARN @wordpress/stylelint-config@19.1.0 requires a peer of stylelint@^13.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @wordpress/eslint-plugin@9.3.0 requires a peer of eslint@^6 || ^7 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@4.33.0 requires a peer of eslint@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@4.33.0 requires a peer of eslint@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsdoc@36.1.1 requires a peer of eslint@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended-scss@4.3.0 requires a peer of stylelint@^10.1.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@5.0.0 requires a peer of stylelint@^13.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-scss@3.21.0 requires a peer of stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mr-dagarna@1.0.0 No repository field.`

**Comment by KristofferBroberg** [comment]
I'm on a Mac btw.

**Comment by KristofferBroberg** [comment]
Finally, it's working! This of course had to do with the whole Node/npm dependency nightmare.
