### ISSUE TITLE
Block patterns in the Advanced Theme Type  trigger an error when using Gutenberg Plugin.

### ISSUE THREAD

**Issue by etherealite** [carolinan/fullsiteediting#21]
I'm using the Gutenberg plugin built from trunk [10d43678b3](https://github.com/WordPress/gutenberg/tree/10d43678b3f5a8856fb3e7ad24ace2b470b27b02) with a Wordpress install of version 5.9.3.  

I created an advanced theme using the generator and 
upon activation I am met with errors for each block pattern file in the patterns directory of the theme. Each error is triggered from this [line](https://github.com/WordPress/gutenberg/blob/10d43678b3f5a8856fb3e7ad24ace2b470b27b02/lib/compat/wordpress-6.0/block-patterns.php#L111) of the Gutenberg plugin's Wordpress 6.0 /lib/compat files

> "Could not register file "/wordpress/wp-content/themes/advanced_generated/patterns/404.php" as a block pattern ("Slug" field missing)"

I was able to get rid of the error by disabling lib/compat hook that is trying to autoload the block patterns by adding the following to the theme's `functions.php` file:

```php
function disable_guttenberg_plugin_pattern_loader() {
	remove_action ('init', 'gutenberg_register_theme_block_patterns');
}
add_action('after_setup_theme', 'disable_guttenberg_plugin_pattern_loader');
```

**Comment by carolinan** [comment]
Thank you, I plan to update this to support the new way of loading patterns after the release of Gutenberg 13.0 :)
