### ISSUE TITLE
Fuzzy shadows?

### ISSUE THREAD

**Issue by jcoonrod** [carolinan/fullsiteediting#26]
Your theme generator is great - but somehow when I created an advanced one I get fuzzy shadows behind the post-titles, and cannot figure out why. I saw a text shadow line in theme.json and removed it, but that did not seem to solve it.
![image](https://user-images.githubusercontent.com/54367582/171873659-b0edd85b-9824-4fb0-a0ed-d3cfeace0e8d.png)

**Comment by carolinan** [comment]
Hi!
The text shadow in theme.json generates a CSS custom property. Removing the style should make sure that the CSS custom property has no value and the shadow should not be applied anymore.
Did you clear cache?

If you look at the light color scheme in the advanced theme version (6.0):
https://github.com/carolinan/fullsiteediting/blob/course/Starter%20themes/advanced-60/styles/light.json#L34
You can see how I updated the shadow to look better on light background.

The generator is not smart enough to know if you selected a light or dark background, so it can't adapt the text shadow, you would need to update the values yourself.

The text shadow is a custom block style, so you can also select the post title -and any of the other blocks that have this option: and deselect the shadow:

![image](https://user-images.githubusercontent.com/7422055/172418724-202115b5-e6ed-40b8-8e02-14672db2a1cc.png)

If you want to remove the optional custom block style from the theme, delete it from inc\register-block-styles.php. Remember to also update the stylesheets and generate new minified versions of the styles.

**Comment by jcoonrod** [comment]
Thanks! Will do!

**Comment by carolinan** [comment]
Closing as solved
