### ISSUE TITLE
Text bumping up against edge of browser window between certain breakpoint

### ISSUE THREAD

**Issue by LukaszJaro** [carolinan/fullsiteediting#27]
Hi @carolinan!,

Between 1024px and 1400px (the wide size I choose in theme.json) the text content is right up against the edge of the browser window. Here's the relevant styles:

```
@media (max-width: 1024px)
main > :not(.alignfull), main .wp-block-query > :not(.alignfull), main .entry-content > :not(.alignfull):not(ul):not(ol), main .entry-content .wp-block-columns.alignfull p {
    padding-left: var(--wp--custom--h-spacing);
    padding-right: var(--wp--custom--h-spacing);
}

.wp-container-51 > .alignwide {
    max-width: 1400px;
}
```

The header is actually ok as you can see, but the post content is not.

The only solution I tried so far is to add a white background to the main group holding the post content which then added too much padding. To fix that I removed the custom media query listed above which was adding excess padding and then everything lined up beautifully.

You can also just set the left/right padding in the dimensions panel.

Then the problem is you can't add full width content that stretches edge to edge. I see some FSE themes like wpfrost using negative margins to combat that.

Or alignfull can get some padding and the main element can be alignfull and then each section can be wrapped in a group with either wide or full width depending on needs. In this case the custom media query would most likely also have to be removed.

What do you think?

![image](https://user-images.githubusercontent.com/10998875/173929615-b284e45d-354a-4df8-a19f-0bb38d27d5b3.png)

**Comment by carolinan** [comment]
Hi
I am still hoping that WordPress / Gutenberg will solve this for us: [see PR #41377.](https://github.com/WordPress/gutenberg/pull/41377)
If I can choose between additional padding and using negative margins, I would prefer the former but this is only my preference. The PR above uses both.

I am trying to look at how other FSE theme authors are solving it, some are using the negative margin, and some are not addressing it at all.

**Comment by LukaszJaro** [comment]
Thanks @carolinan. Will keep a eye on that ticket, Looks like it will still be wild west and custom solutions until then.

**Comment by LukaszJaro** [comment]
Looks like the PR was closed, do you know if it properly addressed this issue?

**Comment by LukaszJaro** [comment]
You're way ahead and already wrote about it here, thank you! Tested and it solved my issue of text bumping against edge of screen.

https://fullsiteediting.com/lessons/theme-json-layout-and-spacing-options/#h-padding-aware-alignments

Also had to remove this temp fix:
```
/*
 * Increase horizontal padding on smaller screens.
 * Temporary solution to avoid text content
 * running up to the edge of the browser window,
 * making the text difficult to read.
*/
@media ( max-width: 1024px ) {

	main > :not(.alignfull),
	main .wp-block-query > :not(.alignfull),
	main .entry-content > :not(.alignfull):not(ul):not(ol),
	main .entry-content .wp-block-columns.alignfull p {
		padding-left: var(--wp--custom--h-spacing);
		padding-right: var(--wp--custom--h-spacing);
	}
}
```

Next will test some full width blocks and see how that is handled with the negative margins.

**Comment by carolinan** [comment]
Yes, I started on an update that will remove that CSS, but then figured it needs to go in a **6.1** theme version, not 6.0, since it requires Gutenberg.
