### ISSUE TITLE
Remove index.php from FSE themes

### ISSUE THREAD

**Issue by LukaszJaro** [carolinan/fullsiteediting#28]
https://make.wordpress.org/core/2022/05/03/wordpress-6-0-field-guide/

This change removes the requirement for block themes to have an unused index.php template just for activation, as they use a templates/index.html file instead. ([#54272](https://core.trac.wordpress.org/ticket/54272))

**Comment by carolinan** [comment]
Hi!
Thank you for taking the time to open the issue.
I am aware, but I can't remove the file until the WordPress.org theme uploader accepts block themes without index.php.

There is also the concern about empty directories ("Silence is golden"), I have not made up my mind about that yet.

**Comment by LukaszJaro** [comment]
There's no harm keeping it. In my case my hosting provider is disabling directory listing so I can safely delete the index.php.

I think I may open this with the WP performance team, as it may potentially have a slight impact on performance by having an extra index blank index file. Maybe have site health warning that there is a blank index.php file which is unnecessary if your current hosting provider has disabled directory listing.

**Comment by carolinan** [comment]
@LukaszJaro   Hi 👋 I have not been able to follow the performance team meetings, do you remember if this has been discussed?
The file requirement has been removed from the theme directory (It uses [Theme Check](https://github.com/WordPress/theme-check/blob/master/changelog.txt#L1)).

**Comment by LukaszJaro** [comment]
Didn't hear anything about that but good to hear about the theme check!
