### ISSUE TITLE
Missing current year in output

### ISSUE THREAD

**Issue by zimnyd** [carolinan/fullsiteediting#34]
https://github.com/carolinan/fullsiteediting/blob/a73b0a70d6d56e2e54a78887cb985dee54f98dc9/Starter%20themes/advanced-61/patterns/footer-links.php#L18

in the line above is mistake. The only word 'Copyright' will be shown but not current year. I think should be like:
`<?php echo esc_html__( 'Copyright', 'full-site-editing' ) . ' ' . esc_html( date_i18n( _x( 'Y', 'copyright date format', 'full-site-editing' ) ) ); ?></p> `

**Comment by carolinan** [comment]
Thank you for the report, I haven't had time to check yet.

**Comment by carolinan** [comment]
Thank you again, I was able to reproduce the problem and your suggestion solves it, I will implement it shortly.
