### ISSUE TITLE
Duotone documentation not showing correctly

### ISSUE THREAD

**Issue by glerner** [carolinan/fullsiteediting#38]
https://fullsiteediting.com/lessons/theme-json-color-options/#h-duotone

Bad Link: <a href="http://WordPress.org: Coloring Your Images With Duotone Filters">WordPress.org: Coloring Your Images With Duotone Filters</a>

Duotones applied to https://fullsiteediting.com/wp-content/uploads/2020/05/wapuu-themes-by-carolina-baloon-250.png are not showing. Styles are not loaded.

**Comment by carolinan** [comment]
Thank you for reporting this! I am not sure if I broke the duotones or if the Gutenberg update broke them 😬
