### ISSUE TITLE
Custom CSS doesn't work on the frontend in classic themes

### ISSUE THREAD

**Issue by mrleemon** [carolinan/fullsiteediting#45]
As reported in this issue:
https://github.com/WordPress/gutenberg/issues/52644

custom CSS (the per-block one, at least) doesn't work on the frontend in classic themes with a theme.json file:
https://fullsiteediting.com/lessons/how-to-use-custom-css-in-theme-json/

Can you add a note indicating this, please?

**Comment by carolinan** [comment]
Hi, it is mentioned here: https://fullsiteediting.com/lessons/adding-full-site-editing-features-to-classic-themes/#h-6-add-theme-json

**Comment by mrleemon** [comment]
Sorry, I can't find any mention in that link about the `styles.blocks.blockname.css` prop not working on the frontend in classic themes.
