### ISSUE TITLE
Broken link on FSE website to github repository.

### ISSUE THREAD

**Issue by impishlycreative** [carolinan/fullsiteediting#49]
Hi Carolina, 

Love FSE.  Searching on the website, it indicates in the contact page that if there are issues with FSE, to log them here.

It looks like you did a consolidation of the github lessons under a different directory.  The following page has a broken URL 
that points to the previous location:

https://fullsiteediting.com/lessons/how-to-use-php-templates-in-block-themes/

The previous location is referred under this section:

_For this example, I will continue using the theme that we created in the previous lessons. You can download the sample theme with the basic templates and theme.json from [GitHub](https://github.com/carolinan/fullsiteediting/tree/course/Block%20based%20themes/Exercise%20-Theme%20json)._

https://github.com/carolinan/fullsiteediting/tree/course/Block%20based%20themes/Exercise%20-Theme%20json

Have a good New Year!

**Comment by carolinan** [comment]
Thank you!
