### ISSUE TITLE
contentSize doesn't work in theme.json file

### ISSUE THREAD

**Issue by Sergey98Am** [carolinan/fullsiteediting#50]
On WordPress `6.5.2` version, in the `theme.json` file, I have a following code

```
{
  "version": 2,
  "settings": {
    "layout": {
      "contentSize": "800px"
    }
  }
}
```

But it doesn't work if editing any Post or opening Site Editor

**Post Editing**

![Screenshot from 2024-05-01 15-37-12](https://github.com/carolinan/fullsiteediting/assets/52923458/ed11fc6e-7f4e-4060-8283-541b4d1a61b1)

**Site Editor**

![Screenshot from 2024-05-01 15-37-35](https://github.com/carolinan/fullsiteediting/assets/52923458/fff89c4c-11f7-450f-a1bb-2d9b253c8ccd)

**Comment by carolinan** [comment]
Hi
Please use WordPress support forums for general support requests, this repository are for problems on fullsiteediting.com, thank you.

There are no bugs in the code example that you shared. 
I don't know if your file contains anything else, but theme.json is sensitive to typos. The problem may be elsewhere in theme.json, or elsewhere in your theme.

**Comment by Sergey98Am** [comment]
Hi @carolinan, Sorry, I was wrong, but thank you anyway.
