### ISSUE TITLE
Button Hover state Color

### ISSUE THREAD

**Issue by Gualtio** [carolinan/fullsiteediting#51]
It would be great if you could decide the color of the button in the hover state directly from the editor styles and not just from the json

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by carolinan** [comment]
I have deleted the spam reply.

Please know that this repository is for the website and not for requesting features for the WordPress software.
